# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0002_auto_20171125_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photot',
            field=models.ImageField(upload_to=''),
        ),
    ]
