# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0003_auto_20171125_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
                ('Author', models.CharField(max_length=20)),
            ],
        ),
    ]
