# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0004_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
