# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0006_file_language_file_math_file_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_math',
            name='people',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
