# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0007_file_math_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_language',
            name='people',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file_others',
            name='people',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
